micronaut.server.port=8443
micronaut.server.ssl.enabled=true
micronaut.server.ssl.key-store.path=file:certs/keystore.p12
micronaut.server.ssl.key-store.password=password
micronaut.server.ssl.key-store.type=PKCS12
